BoardCellImportance: |-
  8 5 4 4 4 4 5 8
  5 4 3 2 2 3 4 5
  4 3 2 2 2 2 3 4
  4 2 2 1 1 2 2 4
  4 2 2 1 1 2 2 4
  4 3 2 2 2 2 3 4
  5 4 3 2 2 3 4 5
  8 5 4 4 4 4 5 8

# Points given to the number of possible moves of the enemy
EnemyPossibleMoveScore: -1

# Point multiplier for the ammount of disk flipped
FlipAmountMultiplier: 1.25

# Score to give if the enemy cannot play
EnemyCannotPlayScore: 1000.0

# Score to give if a game ending is found
GameOverScore: 100000.0

Depth: 3
