
# Recusion depth
Depth: 3

# score to give to each cell
BoardCellImportance: |-
  9 1 1 1 1 1 1 9
  1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1
  9 1 1 1 1 1 1 9

CellImportanceMultiplier: 0.75

# Points given to the number of possible moves of the enemy
EnemyPossibleMoveScore: -5

# Point multiplier for the ammount of disk flipped
FlipAmountMultiplier: 1.5

# Score to give if a game ending is found
GameOverScore: 1000000.0

# Score to give if the enemy cannot play
EnemyCannotPlayScore: 1000.0

# How much does the score of the enemy matters
EnemyScoreMultiplier: -2

# How much score to give for each pieces the enemy owns
EnemyPiecesScore: -2

# How much score to give for each of our pieces
CurrentPiecesScore: 2
