on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

jobs:

  build:
    name: C# Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --logger:"trx;LogFileName=${{ github.workspace }}/TestsResults.trx;"

    - name: Upload Tests Results
      uses: actions/upload-artifact@v2
      with:
        name: 'Test Run'
        path: ${{ github.workspace }}/TestsResults.trx

  publish:
    name: C# Publish to Nuget
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Packing
        run: dotnet pack ./Reversi/Reversi.csproj

      - name: Nuget Pushing
        run: |
          dotnet nuget push \
          ./Reversi/bin/Debug/ApolloRoboto.Reversi.*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json